### ISSUE TITLE
update README with new guidelines

### ISSUE THREAD

**Issue by pejg12** [janaxs/javascript-style-guide#3]
There has been changes to the tests and configs not yet reflected in the README document.

I'm thinking specifically of the case with `function ()` vs `function()` but there may be more.

Commit: [117eaf6](https://github.com/janaxs/javascript-style-guide/commit/117eaf669d708191632c5084abd0e0e52f0f7b83)
README: [Whitespace](https://github.com/janaxs/javascript-style-guide#whitespace)

**Comment by mosbth** [comment]
Fixed in https://github.com/janaxs/javascript-style-guide/commit/093c3e1771f4877a0be8a849b32bacd51171b382
