### ISSUE TITLE
Semicolons and soft tab indentation

### ISSUE THREAD

**Issue by litemerafrukt** [janaxs/javascript-style-guide#4]
If the intended audience primarily is dbwebb students I think the phrasing for using semicolons could be changed from: "You can decide on wether to use semicolon or not (dbwebb requires semicolon)." to "Use semicolons".

Likewise for soft tab size, dbwebb validator requires you to use 4 spaces, and the phrasing could be changed from "Tab size can be 2 or 4 (dbwebb uses 4)." to "Use 4 spaces for indentation."

**Comment by mosbth** [comment]
Fixed in https://github.com/janaxs/javascript-style-guide/commit/093c3e1771f4877a0be8a849b32bacd51171b382
